INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(100,'hasith','Learn Cloud',DATEADD('YEAR', 2, CURRENT_DATE),false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(110,'hasith','Learn AWS',DATEADD('YEAR', 2, CURRENT_DATE),false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(120,'hasith','Learn Springboot',DATEADD('YEAR', 1, CURRENT_DATE),false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(130,'hasith','Learn Docker',DATEADD('MONTH', 6, CURRENT_DATE),false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(140,'hasith','Learn Python',DATEADD('YEAR', 1, CURRENT_DATE),false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(150,'hasith','Learn No SQL Databases',DATEADD('YEAR', 1, CURRENT_DATE),false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(160,'hasith','Learn functional programming',DATEADD('YEAR', 1, CURRENT_DATE),false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(170,'hasith','Read books about Servlets',DATEADD('YEAR', 1, CURRENT_DATE),false);